// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Transportes_API.Models;

public partial class Camiones
{
    [Key]
    public int ID_camiones { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string matricula { get; set; }

    public int capacidad { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string tipo_camion { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string urlfoto { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string marca { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string modelo { get; set; }

    public double kilometraje { get; set; }

    public bool disponibilidad { get; set; }
}