// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Transportes_API.Models;

public partial class TransportesContext : DbContext
{
    public TransportesContext(DbContextOptions<TransportesContext> options)
        : base(options)
    {

    }

    public virtual DbSet<Camiones> Camiones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Camiones>(entity =>
        {
            entity.HasKey(e => e.ID_camiones).HasName("PK__Camiones__B10075A35E5B0903");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}